### ISSUE TITLE
Refactoring building with supplements

### ISSUE THREAD

**Issue by ghost** [mtgjson/mtgsqlive#55]
You could use a list, loop the list for each value instead of reapiting the same code. The list would be: ["AllPrices.json", "AllDeckFiles", "Keywords.json", "Card Types"]

**Comment by omfgitsmark** [comment]
The only issue is some of them are files and some are directories, but I see your point and can make it work. I'm going to have to rework this script soon for v5 anyways and was planning on cleaning it up while I did since I haven't had to touch it in a while, so I will plan to take care of this then.

Thanks for the suggestion! Feel free to submit PRs for any more minor improvements you come across.

**Comment by omfgitsmark** [comment]
Fixed in #57
