### ISSUE TITLE
Changes to the "finishes" column

### ISSUE THREAD

**Issue by SteButler** [mtgjson/mtgsqlive#75]
The following refers to the mysql output, not sure if its different anywhere else : 

My assumption is that the "finishes" column will eventually supercede the "hasfoil" and "hasnonfoil" attributes, and they will be removed - however, there is a particular step backwards in that you can't now search for "foil" in the finishes column, as it brings back "nonfoil" as well - there is no distinct word to find just foils - _can the content be changed to "F", "N", and "E"?_

Alternatively, If this isn't the case, and the hasFoil and hasNonFoil attributes are here to stay, then _can we get a hasEtched as well for consistency?_

**Comment by van-riper** [comment]
As of version 5.2.0, `hasFoil` and `hasNonFoil` are deprecated, which means that they are no longer supported and will possibly be removed from future versions. The new `finishes` model is in practice much more consistent also.

**Comment by SteButler** [comment]
Thanks, that makes sense (and is a good change) - so makes the first point more pressing EG : 

SELECT * FROM mtgincoming.cards where name LIKE 'shock' where finishes LIKE '%foil%'

This brings back both foil and non foils - is there a better way?

**Comment by drewmie** [comment]
I agree that it's problematic to call them "nonfoil" since the word "foil" is still part of that word.  It also implies a binary foil/nonfoil which is no longer as accurate.  Also, WotC may do more finishes in the future, and they may even update the "normal" finish to something else.  Looking forward to "engraved" and "A.I. 3D holograph" finishes anyone?  ;)

Tcgplayer actually does it better by designating them as "normal" instead of "nonfoil".  But they unfortunately dropped the ball on "etched" by flagging it as foil and specifying "etched foil" in the name.  Ugh.  My kingdom for some consistency!

Suggestion:  Could we change the finishes from "nonfoil" to something like "normal"?  (or even better: "original" in case they change the norm)

**Comment by ZeldaZach** [comment]
As of the moment, that's the agreed upon standard ("nonfoil" meaning "original") and I'd like to keep in line with what other providers use / expect
